
name: Publish Docker image

on:
  push:
    branches: main
    
    tags:
      - v*
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: nginx

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: tnmnet/uscis-speed-test
          tags: ${{ github.sha }}
          dockerfile: Dockerfile

 
